INSERT INTO `users` (`email`, `lastname`, `firstname`, `department`, `status`) VALUES
('', '','Cisco Conference Room','','4'),
('', '','Company Hardware','','4'),
('', '','Spectralink Hardware','','4'),
('chris.chares@303software.com', 'Chares','Chris','2','1'),
('keith@303software.com', 'Decker','Keith','1','1'),
('damon@303software.com', 'Delgado','Damon','4','1'),
('don@303software.com', 'Downing','Don','2','1'),
('eadoxy@303software.com', 'Doxy','Elizabeth','2','1'),
('chase.foster@303software.com', 'Foster','Chase','2','1'),
('Gantulga@303software.com', 'Gansukh','Gantulga','2','1'),
('tierreg@303software.com', 'Gillespie','Tierre','3','1'),
('matt@303software.com', 'Jaffe','Matt','2','1'),
('', 'Metrailer','Trey','','3'),
('', 'Michael','Sean','','3'),
('', 'Opalla','Chris','','2'),
('cass@303software.com', 'Pangell','Cassidy','2','1'),
('mike.petersen@303software.com', 'Petersen','Mike','5','1'),
('scott@303software.com', 'Quinney','Scott','2','1'),
('', 'Ramsbott','Pam','','3'),
('stefan@303software.com', 'Ramsbott','Stefan','5','1'),
('michelle@303software.com', 'Resnick','Michelle','2','1'),
('', 'Schroeder','Karl','','3'),
('derek@303software.com', 'Taniguchi','Derek','3','1'),
('dave.twiggs@303software.com', 'Twiggs','Dave','2','1'),
('hannah@303software.com', 'Wright','Hannah','3','1'),
('david.yoakum@303software.com', 'Yoakum','David','2','1');
